### ISSUE TITLE
Почему, а главное, зачем

### ISSUE THREAD

**Issue by LDelOff** [SovietHub/SQL-Table-1.1.3-#1]
в методе removeUserById (UserDaoJDBXImpl) почему-то не юзается id

**Comment by SovietHub** [comment]
В классе UserDaoJDBXImpl метода removeUserById(long id) в строчке 62 прописан SQL-скрипт:
"DELETE FROM `Persons`  WHERE id = '?'"
Который говорит о том, что удаление происходит из таблицы Persons по id
Где знак '?' означает, что данный параметр будет заменён на входящий параметр сигнатуры метода(long id)
Если бы было несколько ? и несколько переменных типа long, пришлось бы прописывать отдельно имена к каждой, чтобы SQL понял к кому какой соотносить

**Comment by LDelOff** [comment]
у меня ругался на то, что ожидалось число, а пришла строка
кароч убрал кавычки и всё-таки впихнул как параметр

**Comment by LDelOff** [comment]
"INSERT INTO `Persons`" + "(name, lastName, age) VALUES (?, ?, ?)"); - тут кавычек нет (49 строка)
"DELETE FROM Persons WHERE id = '?'" - а тут есть
я про это

**Comment by LDelOff** [comment]
я про это

**Comment by SovietHub** [comment]
Да, необходимо писать "DELETE FROM Persons WHERE id = ?"
Иначе id воспринимается как Spring
